LojaDeDisco/LojaDeDisco.Api/Models/Autor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LojaDeDisco.Api.Models
{
	public class Autor
	{
		public int Id { get; set; }
		public string NomeAutor { get; set; }
		public int? AutorPaiId { get; set; }
		[ForeignKey("AutorPaiId")]
		public Autor AutorPai { get; set; }
		public List<Titulo> Titulos { get; set; }
		[InverseProperty("AutorPai")]
		public List<Autor> Filhos { get; set; }
	}
}

LojaDeDisco/LojaDeDisco.Api/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaDeDisco.Api.Models;

namespace LojaDeDisco.Api.Controllers
{
    public class AutorController : Controller
    {
        private LojaDeDiscoContext db = new LojaDeDiscoContext();

        // GET: /Autor/
        public ActionResult Index()
        {
            var autores = db.Autores
				.Include(a => a.Filhos).Include(a => a.AutorPai)
				.Where(a => a.AutorPaiId == null);
			return View(autores.ToList());
        }

		public ActionResult GetFilho(int id = 0)
		{
			var autores = db.Autores
				.Include(a => a.Filhos).Include(a => a.AutorPai)
				.Where(a => a.AutorPaiId == id || (a.AutorPaiId == null && id == 0));
			return View(autores.OrderBy(x => x.NomeAutor).ToList());
		}

		private void ToList()
		{
			throw new NotImplementedException();
		}
        // GET: /Autor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autores.Include(a => a.AutorPai).FirstOrDefault(a => a.Id == id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // GET: /Autor/Create
        public ActionResult Create()
        {
            ViewBag.AutorPaiId = new SelectList(db.Autores, "Id", "NomeAutor");
            return View();
        }

        // POST: /Autor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,NomeAutor,AutorPaiId")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Autores.Add(autor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AutorPaiId = new SelectList(db.Autores, "Id", "NomeAutor", autor.AutorPaiId);
            return View(autor);
        }

        // GET: /Autor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autores.Find(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            ViewBag.AutorPaiId = new SelectList(db.Autores, "Id", "NomeAutor", autor.AutorPaiId);
            return View(autor);
        }

        // POST: /Autor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,NomeAutor,AutorPaiId")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AutorPaiId = new SelectList(db.Autores, "Id", "NomeAutor", autor.AutorPaiId);
            return View(autor);
        }

        // GET: /Autor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autores.Find(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // POST: /Autor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Autor autor = db.Autores.Find(id);
            db.Autores.Remove(autor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaDeDisco/LojaDeDisco.Api/Views/Autor/Create.cshtml
@model LojaDeDisco.Api.Models.Autor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autor</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeAutor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeAutor)
                @Html.ValidationMessageFor(model => model.NomeAutor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutorPaiId, "AutorPaiId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AutorPaiId", String.Empty)
                @Html.ValidationMessageFor(model => model.AutorPaiId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LojaDeDisco/LojaDeDisco.Api/Views/Autor/Delete.cshtml
@model LojaDeDisco.Api.Models.Autor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Autor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AutorPai.NomeAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutorPai.NomeAutor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeAutor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LojaDeDisco/LojaDeDisco.Api/Views/Autor/Details.cshtml
@model LojaDeDisco.Api.Models.Autor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Autor</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AutorPai.NomeAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutorPai.NomeAutor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeAutor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LojaDeDisco/LojaDeDisco.Api/Views/Autor/Edit.cshtml
@model LojaDeDisco.Api.Models.Autor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autor</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeAutor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeAutor)
                @Html.ValidationMessageFor(model => model.NomeAutor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutorPaiId, "AutorPaiId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AutorPaiId", String.Empty)
                @Html.ValidationMessageFor(model => model.AutorPaiId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LojaDeDisco/LojaDeDisco.Api/Views/Autor/GetFilho.cshtml
@model IEnumerable<LojaDeDisco.Api.Models.Autor>
@{
	Layout = null;
}
@foreach (var item in Model)
{
	<div class="row" style="border-bottom: #000099 1px dotted;">
		<span class="col-md-3 col-xs-6">
			@if (item.Filhos.Count > 0)
			{
				<span id="@(item.Id)" class="btn-default botao-mais" onclick="CarregarSubitens('@(item.Id)');">
					<span class="glyphicon glyphicon-plus-sign" id="@(item.Id)_button"></span>Ver subitens
				</span>
			}
		</span>
		<span class="col-md-3 col-xs-6">@Html.DisplayFor(modelItem => item.NomeAutor)</span>
		<span class="col-md-2 col-xs-4">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</span>
		<span class="col-md-2 col-xs-4">@Html.ActionLink("Details", "Details", new { id = item.Id }) </span>
		<span class="col-md-2 col-xs-4">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</span>
		<span class="clearfix"></span>
		@if (item.Filhos.Count > 0)
		{
			<div id="@(item.Id)_container" class="col-md-12"></div>
		}
	</div>
}

LojaDeDisco/LojaDeDisco.Api/Views/Autor/Index.cshtml
@model IEnumerable<LojaDeDisco.Api.Models.Autor>

@{
	ViewBag.Title = "Index";
}

<script type="text/javascript" language="javascript">
	function CarregarSubitens(id) {
		if ($("#" + id + "_button").hasClass("glyphicon-plus-sign")) {
			$("#" + id + "_container").load("/autor/GetFilho/" + id);
			$("#" + id + "_button")
				.removeClass("glyphicon-plus-sign")
				.addClass("glyphicon-minus-sign");
		} else {
			$("#" + id + "_container").empty();
			$("#" + id + "_button")
				.removeClass("glyphicon-minus-sign")
				.addClass("glyphicon-plus-sign");
		}
	}
	$(document).ready(function () {
	});
</script>

<h2>Index</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>
<div class="row">
	<div class="row h3">
		<span class="col-md-3 col-xs-6">Integrantes</span>
		<span class="col-md-3 col-xs-6">@Html.DisplayNameFor(model => model.NomeAutor)</span>
		<span class="col-md-6 col-xs-12">
		</span>
	</div>
	<div class="row">
		@Html.Action("GetFilho", "Autor")
	</div>
</div>